$(function() {
    _dropoffUrlParam_();
    $('body').show();

    var textTypeSpan = $('.text-type span');
    textTypeSpan.click(function () {
        textTypeSpan.removeClass('active');
        $(this).addClass('active');

        btnSelectList.hide();
        var textType = textTypeSpan.siblings('.active').prop('class').split(/\s+/)[0];
        if (textType == 'sql') btnSelectList.filter('.sql-type').show();
        else if (textType == 'num') btnSelectList.filter('.num-type').show();
    });

    var shiftTypeB = $('.shift-type b');
    shiftTypeB.click(function () {
        shiftTypeB.removeClass('active');
        $(this).addClass('active');
    });

    $('.main-shell').click(function () {
        $('.ext-widget-list').hide();
        $('.ext-widget-button.toggle-arrow').removeClass('up-arrow').addClass('down-arrow');
    });
    var btnSelectList = $('.btn-select-list');
    var btnSelect = $('.btn-select');
    var extWidgetList = $('.ext-widget-list');
    btnSelect.click(function (e) {
        e.stopPropagation();
        e.preventDefault();
        var thisList = $(this).siblings('.ext-widget-list');
        var otherList = $('.ext-widget-list').not(thisList[0]);
        var otherButton = $('.btn-select').not(this).children('.ext-widget-button');
        var thisButton = $(this).children('.ext-widget-button');
        if (otherButton.hasClass('up-arrow')) otherButton.removeClass('up-arrow').addClass('down-arrow');
        if (thisButton.hasClass('up-arrow')) {
            thisButton.removeClass('up-arrow').addClass('down-arrow');
        } else {
            thisButton.removeClass('down-arrow').addClass('up-arrow');
        }
        otherList.hide();
        thisList.toggle();
    });
    extWidgetList.find('li').click(function () {
        var thisSelect = $(this).parent().siblings('.btn-select');
        var thisButton = thisSelect.children('.ext-widget-button');
        var thisInput = thisSelect.children('input');
        if (thisButton.hasClass('up-arrow')) thisButton.removeClass('up-arrow').addClass('down-arrow');
        thisInput.val($(this).text());
        thisInput.attr('select', $(this).prop('class'));
    });

    var taSource = $('#taSource');
    var taResult = $('#taResult');

    var btnClear = $('#btnClear');
    btnClear.click(function () {
        taSource.val('');
        taResult.val('');
    });

    var btnShift = $('#btnShift');
    btnShift.click(function () {
        var textType = textTypeSpan.siblings('.active').prop('class').split(/\s+/)[0];
        var shiftType = shiftTypeB.siblings('.active').prop('class').split(/\s+/)[0];
        var taSrcVal = taSource.val();
        var taRstVal;

        if (textType == 'char') {
            taRstVal = (shiftType == 'upper') ? taSrcVal.toUpperCase() : taSrcVal.toLowerCase();
        } else if (textType == 'sql') {
            var sqlType = $('#sqlType').attr('select');
            var sqlSelect = [];
            if (sqlType == 'sql1992') sqlSelect = sqlset['sql1992'];
            else if (sqlType == 'sql1999') sqlSelect = sqlset['sql1999'];
            else if (sqlType == 'sql2003') sqlSelect = sqlset['sql2003'];
            else if (sqlType == 'sql2008') sqlSelect = sqlset['sql2008'];
            else if (sqlType == 'sql2011') sqlSelect = sqlset['sql2011'];
            else sqlSelect = sqlset['sqlall'];
            if (shiftType == 'upper') {
                sqlSelect.forEach(function (kw) {
                    taSrcVal = taSrcVal.replace(new RegExp('(^|\\s+)' + kw + '(\\s+|;|$)', 'ig'), '$1' + kw.toUpperCase() + '$2');
                });
            } else {
                sqlSelect.forEach(function (kw) {
                    taSrcVal = taSrcVal.replace(new RegExp('(^|\\s+)' + kw + '(\\s+|;|$)', 'ig'), '$1' + kw.toLowerCase() + '$2');
                });
            }
            taRstVal = taSrcVal;
        } else if (textType == 'num') {
            var numType = $('#numType').attr('select');
            var numSelect = [];
            if (numType == 'money') {
                if (shiftType == 'upper') {
                    taSrcVal = num2money(taSrcVal);
                } else {
                    taSrcVal = money2num(taSrcVal);
                }
            } else {
                if (numType == 'simple') numSelect = numset['simple'];
                else numSelect = numset['complex'];
                if (shiftType == 'upper') {
                    numSelect.forEach(function (kw, i) {
                        taSrcVal = taSrcVal.replace(new RegExp(i + '', 'ig'), kw);
                    });
                } else {
                    numSelect.forEach(function (kw, i) {
                        taSrcVal = taSrcVal.replace(new RegExp(kw, 'ig'), i + '');
                    });
                }
            }
            taRstVal = taSrcVal;
        }

        taResult.val(taRstVal);
    });
});

var sqlset = [];
sqlset['sql1992'] = ['ABSOLUTE','ACTION','ADD','ALL','ALLOCATE','ALTER','AND','ANY','ARE','AS','ASC','ASSERTION','AT','AUTHORIZATION','AVG','BEGIN','BETWEEN','BIT','BIT_LENGTH','BOTH','BY','CASCADE','CASCADED','CASE','CAST','CATALOG','CHAR','CHARACTER','CHARACTER_LENGTH','CHAR_LENGTH','CHECK','CLOSE','COALESCE','COLLATE','COLLATION','COLUMN','COMMIT','CONNECT','CONNECTION','CONSTRAINT','CONSTRAINTS','CONTINUE','CONVERT','CORRESPONDING','COUNT','CREATE','CROSS','CURRENT','CURRENT_DATE','CURRENT_TIME','CURRENT_TIMESTAMP','CURRENT_USER','CURSOR','DATE','DAY','DEALLOCATE','DEC','DECIMAL','DECLARE','DEFAULT','DEFERRABLE','DEFERRED','DELETE','DESC','DESCRIBE','DESCRIPTOR','DIAGNOSTICS','DISCONNECT','DISTINCT','DOMAIN','DOUBLE','DROP','ELSE','END','END-EXEC','ESCAPE','EXCEPT','EXCEPTION','EXEC','EXECUTE','EXISTS','EXTERNAL','EXTRACT','FALSE','FETCH','FIRST','FLOAT','FOR','FOREIGN','FOUND','FROM','FULL','GET','GLOBAL','GO','GOTO','GRANT','GROUP','HAVING','HOUR','IDENTITY','IMMEDIATE','IN','INDICATOR','INITIALLY','INNER','INPUT','INSENSITIVE','INSERT','INT','INTEGER','INTERSECT','INTERVAL','INTO','IS','ISOLATION','JOIN','KEY','LANGUAGE','LAST','LEADING','LEFT','LEVEL','LIKE','LOCAL','LOWER','MATCH','MAX','MIN','MINUTE','MODULE','MONTH','NAMES','NATIONAL','NATURAL','NCHAR','NEXT','NO','NOT','NULL','NULLIF','NUMERIC','OCTET_LENGTH','OF','ON','ONLY','OPEN','OPTION','OR','ORDER','OUTER','OUTPUT','OVERLAPS','PAD','PARTIAL','POSITION','PRECISION','PREPARE','PRESERVE','PRIMARY','PRIOR','PRIVILEGES','PROCEDURE','PUBLIC','READ','REAL','REFERENCES','RELATIVE','RESTRICT','REVOKE','RIGHT','ROLLBACK','ROWS','SCHEMA','SCROLL','SECOND','SECTION','SELECT','SESSION','SESSION_USER','SET','SIZE','SMALLINT','SOME','SPACE','SQL','SQLCODE','SQLERROR','SQLSTATE','SUBSTRING','SUM','SYSTEM_USER','TABLE','TEMPORARY','THEN','TIME','TIMESTAMP','TIMEZONE_HOUR','TIMEZONE_MINUTE','TO','TRAILING','TRANSACTION','TRANSLATE','TRANSLATION','TRIM','TRUE','UNION','UNIQUE','UNKNOWN','UPDATE','UPPER','USAGE','USER','USING','VALUE','VALUES','VARCHAR','VARYING','VIEW','WHEN','WHENEVER','WHERE','WITH','WORK','WRITE','YEAR','ZONE'];
sqlset['sql1999'] = ['ABSOLUTE','ACTION','ADD','ADMIN','AFTER','AGGREGATE','ALIAS','ALL','ALLOCATE','ALTER','AND','ANY','ARE','ARRAY','AS','ASC','ASSERTION','AT','AUTHORIZATION','BEFORE','BEGIN','BINARY','BIT','BLOB','BOOLEAN','BOTH','BREADTH','BY','CALL','CASCADE','CASCADED','CASE','CAST','CATALOG','CHAR','CHARACTER','CHECK','CLASS','CLOB','CLOSE','COLLATE','COLLATION','COLUMN','COMMIT','COMPLETION','CONNECT','CONNECTION','CONSTRAINT','CONSTRAINTS','CONSTRUCTOR','CONTINUE','CORRESPONDING','CREATE','CROSS','CUBE','CURRENT','CURRENT_DATE','CURRENT_PATH','CURRENT_ROLE','CURRENT_TIME','CURRENT_TIMESTAMP','CURRENT_USER','CURSOR','CYCLE','DATA','DATE','DAY','DEALLOCATE','DEC','DECIMAL','DECLARE','DEFAULT','DEFERRABLE','DEFERRED','DELETE','DEPTH','DEREF','DESC','DESCRIBE','DESCRIPTOR','DESTROY','DESTRUCTOR','DETERMINISTIC','DIAGNOSTICS','DICTIONARY','DISCONNECT','DISTINCT','DOMAIN','DOUBLE','DROP','DYNAMIC','EACH','ELSE','END','END-EXEC','EQUALS','ESCAPE','EVERY','EXCEPT','EXCEPTION','EXEC','EXECUTE','EXTERNAL','FALSE','FETCH','FIRST','FLOAT','FOR','FOREIGN','FOUND','FREE','FROM','FULL','FUNCTION','GENERAL','GET','GLOBAL','GO','GOTO','GRANT','GROUP','GROUPING','HAVING','HOST','HOUR','IDENTITY','IGNORE','IMMEDIATE','IN','INDICATOR','INITIALIZE','INITIALLY','INNER','INOUT','INPUT','INSERT','INT','INTEGER','INTERSECT','INTERVAL','INTO','IS','ISOLATION','ITERATE','JOIN','KEY','LANGUAGE','LARGE','LAST','LATERAL','LEADING','LEFT','LESS','LEVEL','LIKE','LIMIT','LOCAL','LOCALTIME','LOCALTIMESTAMP','LOCATOR','MAP','MATCH','MINUTE','MODIFIES','MODIFY','MODULE','MONTH','NAMES','NATIONAL','NATURAL','NCHAR','NCLOB','NEW','NEXT','NO','NONE','NOT','NULL','NUMERIC','OBJECT','OF','OFF','OLD','ON','ONLY','OPEN','OPERATION','OPTION','OR','ORDER','ORDINALITY','OUT','OUTER','OUTPUT','PAD','PARAMETER','PARAMETERS','PARTIAL','PATH','POSTFIX','PRECISION','PREFIX','PREORDER','PREPARE','PRESERVE','PRIMARY','PRIOR','PRIVILEGES','PROCEDURE','PUBLIC','READ','READS','REAL','RECURSIVE','REF','REFERENCES','REFERENCING','RELATIVE','RESTRICT','RESULT','RETURN','RETURNS','REVOKE','RIGHT','ROLE','ROLLBACK','ROLLUP','ROUTINE','ROW','ROWS','SAVEPOINT','SCHEMA','SCOPE','SCROLL','SEARCH','SECOND','SECTION','SELECT','SEQUENCE','SESSION','SESSION_USER','SET','SETS','SIZE','SMALLINT','SOME','SPACE','SPECIFIC','SPECIFICTYPE','SQL','SQLEXCEPTION','SQLSTATE','SQLWARNING','START','STATE','STATEMENT','STATIC','STRUCTURE','SYSTEM_USER','TABLE','TEMPORARY','TERMINATE','THAN','THEN','TIME','TIMESTAMP','TIMEZONE_HOUR','TIMEZONE_MINUTE','TO','TRAILING','TRANSACTION','TRANSLATION','TREAT','TRIGGER','TRUE','UNDER','UNION','UNIQUE','UNKNOWN','UNNEST','UPDATE','USAGE','USER','USING','VALUE','VALUES','VARCHAR','VARIABLE','VARYING','VIEW','WHEN','WHENEVER','WHERE','WITH','WITHOUT','WORK','WRITE','YEAR','ZONE'];
sqlset['sql2003'] = ['ABS','ALL','ALLOCATE','ALTER','AND','ANY','ARE','ARRAY','AS','ASENSITIVE','ASYMMETRIC','AT','ATOMIC','AUTHORIZATION','AVG','BEGIN','BETWEEN','BIGINT','BINARY','BLOB','BOOLEAN','BOTH','BY','CALL','CALLED','CARDINALITY','CASCADED','CASE','CAST','CEIL','CEILING','CHAR','CHARACTER','CHARACTER_LENGTH','CHAR_LENGTH','CHECK','CLOB','CLOSE','COALESCE','COLLATE','COLLECT','COLUMN','COMMIT','CONDITION','CONNECT','CONSTRAINT','CONVERT','CORR','CORRESPONDING','COUNT','COVAR_POP','COVAR_SAMP','CREATE','CROSS','CUBE','CUME_DIST','CURRENT','CURRENT_DATE','CURRENT_DEFAULT_TRANSFORM_GROUP','CURRENT_PATH','CURRENT_ROLE','CURRENT_TIME','CURRENT_TIMESTAMP','CURRENT_TRANSFORM_GROUP_FOR_TYPE','CURRENT_USER','CURSOR','CYCLE','DATE','DAY','DEALLOCATE','DEC','DECIMAL','DECLARE','DEFAULT','DELETE','DENSE_RANK','DEREF','DESCRIBE','DETERMINISTIC','DISCONNECT','DISTINCT','DOUBLE','DROP','DYNAMIC','EACH','ELEMENT','ELSE','END','END-EXEC','ESCAPE','EVERY','EXCEPT','EXEC','EXECUTE','EXISTS','EXP','EXTERNAL','EXTRACT','FALSE','FETCH','FILTER','FLOAT','FLOOR','FOR','FOREIGN','FREE','FROM','FULL','FUNCTION','FUSION','GET','GLOBAL','GRANT','GROUP','GROUPING','HAVING','HOLD','HOUR','IDENTITY','IN','INDICATOR','INNER','INOUT','INSENSITIVE','INSERT','INT','INTEGER','INTERSECT','INTERSECTION','INTERVAL','INTO','IS','JOIN','LANGUAGE','LARGE','LATERAL','LEADING','LEFT','LIKE','LN','LOCAL','LOCALTIME','LOCALTIMESTAMP','LOWER','MATCH','MAX','MEMBER','MERGE','METHOD','MIN','MINUTE','MOD','MODIFIES','MODULE','MONTH','MULTISET','NATIONAL','NATURAL','NCHAR','NCLOB','NEW','NO','NONE','NORMALIZE','NOT','NULL','NULLIF','NUMERIC','OCTET_LENGTH','OF','OLD','ON','ONLY','OPEN','OR','ORDER','OUT','OUTER','OVER','OVERLAPS','OVERLAY','PARAMETER','PARTITION','PERCENTILE_CONT','PERCENTILE_DISC','PERCENT_RANK','POSITION','POWER','PRECISION','PREPARE','PRIMARY','PROCEDURE','RANGE','RANK','READS','REAL','RECURSIVE','REF','REFERENCES','REFERENCING','REGR_AVGX','REGR_AVGY','REGR_COUNT','REGR_INTERCEPT','REGR_R2','REGR_SLOPE','REGR_SXX','REGR_SXY','REGR_SYY','RELEASE','RESULT','RETURN','RETURNS','REVOKE','RIGHT','ROLLBACK','ROLLUP','ROW','ROWS','ROW_NUMBER','SAVEPOINT','SCOPE','SCROLL','SEARCH','SECOND','SELECT','SENSITIVE','SESSION_USER','SET','SIMILAR','SMALLINT','SOME','SPECIFIC','SPECIFICTYPE','SQL','SQLEXCEPTION','SQLSTATE','SQLWARNING','SQRT','START','STATIC','STDDEV_POP','STDDEV_SAMP','SUBMULTISET','SUBSTRING','SUM','SYMMETRIC','SYSTEM','SYSTEM_USER','TABLE','TABLESAMPLE','THEN','TIME','TIMESTAMP','TIMEZONE_HOUR','TIMEZONE_MINUTE','TO','TRAILING','TRANSLATE','TRANSLATION','TREAT','TRIGGER','TRIM','TRUE','UESCAPE','UNION','UNIQUE','UNKNOWN','UNNEST','UPDATE','UPPER','USER','USING','VALUE','VALUES','VARCHAR','VARYING','VAR_POP','VAR_SAMP','WHEN','WHENEVER','WHERE','WIDTH_BUCKET','WINDOW','WITH','WITHIN','WITHOUT','XML','XMLAGG','XMLATTRIBUTES','XMLBINARY','XMLCOMMENT','XMLCONCAT','XMLELEMENT','XMLFOREST','XMLNAMESPACES','XMLPARSE','XMLPI','XMLROOT','XMLSERIALIZE','YEAR'];
sqlset['sql2008'] = ['ABS','ALL','ALLOCATE','ALTER','AND','ANY','ARE','ARRAY','ARRAY_AGG','AS','ASENSITIVE','ASYMMETRIC','AT','ATOMIC','AUTHORIZATION','AVG','BEGIN','BETWEEN','BIGINT','BINARY','BLOB','BOOLEAN','BOTH','BY','CALL','CALLED','CARDINALITY','CASCADED','CASE','CAST','CEIL','CEILING','CHAR','CHARACTER','CHARACTER_LENGTH','CHAR_LENGTH','CHECK','CLOB','CLOSE','COALESCE','COLLATE','COLLECT','COLUMN','COMMIT','CONDITION','CONNECT','CONSTRAINT','CONVERT','CORR','CORRESPONDING','COUNT','COVAR_POP','COVAR_SAMP','CREATE','CROSS','CUBE','CUME_DIST','CURRENT','CURRENT_CATALOG','CURRENT_DATE','CURRENT_DEFAULT_TRANSFORM_GROUP','CURRENT_PATH','CURRENT_ROLE','CURRENT_SCHEMA','CURRENT_TIME','CURRENT_TIMESTAMP','CURRENT_TRANSFORM_GROUP_FOR_TYPE','CURRENT_USER','CURSOR','CYCLE','DATE','DAY','DEALLOCATE','DEC','DECIMAL','DECLARE','DEFAULT','DELETE','DENSE_RANK','DEREF','DESCRIBE','DETERMINISTIC','DISCONNECT','DISTINCT','DOUBLE','DROP','DYNAMIC','EACH','ELEMENT','ELSE','END','END-EXEC','ESCAPE','EVERY','EXCEPT','EXEC','EXECUTE','EXISTS','EXP','EXTERNAL','EXTRACT','FALSE','FETCH','FILTER','FIRST_VALUE','FLOAT','FLOOR','FOR','FOREIGN','FREE','FROM','FULL','FUNCTION','FUSION','GET','GLOBAL','GRANT','GROUP','GROUPING','HAVING','HOLD','HOUR','IDENTITY','IN','INDICATOR','INNER','INOUT','INSENSITIVE','INSERT','INT','INTEGER','INTERSECT','INTERSECTION','INTERVAL','INTO','IS','JOIN','LAG','LANGUAGE','LARGE','LAST_VALUE','LATERAL','LEAD','LEADING','LEFT','LIKE','LIKE_REGEX','LN','LOCAL','LOCALTIME','LOCALTIMESTAMP','LOWER','MATCH','MAX','MAX_CARDINALITY','MEMBER','MERGE','METHOD','MIN','MINUTE','MOD','MODIFIES','MODULE','MONTH','MULTISET','NATIONAL','NATURAL','NCHAR','NCLOB','NEW','NO','NONE','NORMALIZE','NOT','NTH_VALUE','NTILE','NULL','NULLIF','NUMERIC','OCCURRENCES_REGEX','OCTET_LENGTH','OF','OFFSET','OLD','ON','ONLY','OPEN','OR','ORDER','OUT','OUTER','OVER','OVERLAPS','OVERLAY','PARAMETER','PARTITION','PERCENTILE_CONT','PERCENTILE_DISC','PERCENT_RANK','POSITION','POSITION_REGEX','POWER','PRECISION','PREPARE','PRIMARY','PROCEDURE','RANGE','RANK','READS','REAL','RECURSIVE','REF','REFERENCES','REFERENCING','REGR_AVGX','REGR_AVGY','REGR_COUNT','REGR_INTERCEPT','REGR_R2','REGR_SLOPE','REGR_SXX','REGR_SXY','REGR_SYY','RELEASE','RESULT','RETURN','RETURNS','REVOKE','RIGHT','ROLLBACK','ROLLUP','ROW','ROWS','ROW_NUMBER','SAVEPOINT','SCOPE','SCROLL','SEARCH','SECOND','SELECT','SENSITIVE','SESSION_USER','SET','SIMILAR','SMALLINT','SOME','SPECIFIC','SPECIFICTYPE','SQL','SQLEXCEPTION','SQLSTATE','SQLWARNING','SQRT','START','STATIC','STDDEV_POP','STDDEV_SAMP','SUBMULTISET','SUBSTRING','SUBSTRING_REGEX','SUM','SYMMETRIC','SYSTEM','SYSTEM_USER','TABLE','TABLESAMPLE','THEN','TIME','TIMESTAMP','TIMEZONE_HOUR','TIMEZONE_MINUTE','TO','TRAILING','TRANSLATE','TRANSLATE_REGEX','TRANSLATION','TREAT','TRIGGER','TRIM','TRIM_ARRAY','TRUE','TRUNCATE','UESCAPE','UNION','UNIQUE','UNKNOWN','UNNEST','UPDATE','UPPER','USER','USING','VALUE','VALUES','VARBINARY','VARCHAR','VARYING','VAR_POP','VAR_SAMP','WHEN','WHENEVER','WHERE','WIDTH_BUCKET','WINDOW','WITH','WITHIN','WITHOUT','XML','XMLAGG','XMLATTRIBUTES','XMLBINARY','XMLCAST','XMLCOMMENT','XMLCONCAT','XMLDOCUMENT','XMLELEMENT','XMLEXISTS','XMLFOREST','XMLITERATE','XMLNAMESPACES','XMLPARSE','XMLPI','XMLQUERY','XMLSERIALIZE','XMLTABLE','XMLTEXT','XMLVALIDATE','YEAR'];
sqlset['sql2011'] = ['ABS','ALL','ALLOCATE','ALTER','AND','ANY','ARE','ARRAY','ARRAY_AGG','ARRAY_MAX_CARDINALITY','AS','ASENSITIVE','ASYMMETRIC','AT','ATOMIC','AUTHORIZATION','AVG','BEGIN','BEGIN_FRAME','BEGIN_PARTITION','BETWEEN','BIGINT','BINARY','BLOB','BOOLEAN','BOTH','BY','CALL','CALLED','CARDINALITY','CASCADED','CASE','CAST','CEIL','CEILING','CHAR','CHARACTER','CHARACTER_LENGTH','CHAR_LENGTH','CHECK','CLOB','CLOSE','COALESCE','COLLATE','COLLECT','COLUMN','COMMIT','CONDITION','CONNECT','CONSTRAINT','CONTAINS','CONVERT','CORR','CORRESPONDING','COUNT','COVAR_POP','COVAR_SAMP','CREATE','CROSS','CUBE','CUME_DIST','CURRENT','CURRENT_CATALOG','CURRENT_DATE','CURRENT_DEFAULT_TRANSFORM_GROUP','CURRENT_PATH','CURRENT_ROLE','CURRENT_ROW','CURRENT_SCHEMA','CURRENT_TIME','CURRENT_TIMESTAMP','CURRENT_TRANSFORM_GROUP_FOR_TYPE','CURRENT_USER','CURSOR','CYCLE','DATALINK','DATE','DAY','DEALLOCATE','DEC','DECIMAL','DECLARE','DEFAULT','DELETE','DENSE_RANK','DEREF','DESCRIBE','DETERMINISTIC','DISCONNECT','DISTINCT','DLNEWCOPY','DLPREVIOUSCOPY','DLURLCOMPLETE','DLURLCOMPLETEONLY','DLURLCOMPLETEWRITE','DLURLPATH','DLURLPATHONLY','DLURLPATHWRITE','DLURLSCHEME','DLURLSERVER','DLVALUE','DOUBLE','DROP','DYNAMIC','EACH','ELEMENT','ELSE','END','END-EXEC','END_FRAME','END_PARTITION','EQUALS','ESCAPE','EVERY','EXCEPT','EXEC','EXECUTE','EXISTS','EXP','EXTERNAL','EXTRACT','FALSE','FETCH','FILTER','FIRST_VALUE','FLOAT','FLOOR','FOR','FOREIGN','FRAME_ROW','FREE','FROM','FULL','FUNCTION','FUSION','GET','GLOBAL','GRANT','GROUP','GROUPING','GROUPS','HAVING','HOLD','HOUR','IDENTITY','IMPORT','IN','INDICATOR','INNER','INOUT','INSENSITIVE','INSERT','INT','INTEGER','INTERSECT','INTERSECTION','INTERVAL','INTO','IS','JOIN','LAG','LANGUAGE','LARGE','LAST_VALUE','LATERAL','LEAD','LEADING','LEFT','LIKE','LIKE_REGEX','LN','LOCAL','LOCALTIME','LOCALTIMESTAMP','LOWER','MATCH','MAX','MEMBER','MERGE','METHOD','MIN','MINUTE','MOD','MODIFIES','MODULE','MONTH','MULTISET','NATIONAL','NATURAL','NCHAR','NCLOB','NEW','NO','NONE','NORMALIZE','NOT','NTH_VALUE','NTILE','NULL','NULLIF','NUMERIC','OCCURRENCES_REGEX','OCTET_LENGTH','OF','OFFSET','OLD','ON','ONLY','OPEN','OR','ORDER','OUT','OUTER','OVER','OVERLAPS','OVERLAY','PARAMETER','PARTITION','PERCENT','PERCENTILE_CONT','PERCENTILE_DISC','PERCENT_RANK','PERIOD','PORTION','POSITION','POSITION_REGEX','POWER','PRECEDES','PRECISION','PREPARE','PRIMARY','PROCEDURE','RANGE','RANK','READS','REAL','RECURSIVE','REF','REFERENCES','REFERENCING','REGR_AVGX','REGR_AVGY','REGR_COUNT','REGR_INTERCEPT','REGR_R2','REGR_SLOPE','REGR_SXX','REGR_SXY','REGR_SYY','RELEASE','RESULT','RETURN','RETURNS','REVOKE','RIGHT','ROLLBACK','ROLLUP','ROW','ROWS','ROW_NUMBER','SAVEPOINT','SCOPE','SCROLL','SEARCH','SECOND','SELECT','SENSITIVE','SESSION_USER','SET','SIMILAR','SMALLINT','SOME','SPECIFIC','SPECIFICTYPE','SQL','SQLEXCEPTION','SQLSTATE','SQLWARNING','SQRT','START','STATIC','STDDEV_POP','STDDEV_SAMP','SUBMULTISET','SUBSTRING','SUBSTRING_REGEX','SUCCEEDS','SUM','SYMMETRIC','SYSTEM','SYSTEM_TIME','SYSTEM_USER','TABLE','TABLESAMPLE','THEN','TIME','TIMESTAMP','TIMEZONE_HOUR','TIMEZONE_MINUTE','TO','TRAILING','TRANSLATE','TRANSLATE_REGEX','TRANSLATION','TREAT','TRIGGER','TRIM','TRIM_ARRAY','TRUE','TRUNCATE','UESCAPE','UNION','UNIQUE','UNKNOWN','UNNEST','UPDATE','UPPER','USER','USING','VALUE','VALUES','VALUE_OF','VARBINARY','VARCHAR','VARYING','VAR_POP','VAR_SAMP','VERSIONING','WHEN','WHENEVER','WHERE','WIDTH_BUCKET','WINDOW','WITH','WITHIN','WITHOUT','XML','XMLAGG','XMLATTRIBUTES','XMLBINARY','XMLCAST','XMLCOMMENT','XMLCONCAT','XMLDOCUMENT','XMLELEMENT','XMLEXISTS','XMLFOREST','XMLITERATE','XMLNAMESPACES','XMLPARSE','XMLPI','XMLQUERY','XMLSERIALIZE','XMLTABLE','XMLTEXT','XMLVALIDATE','YEAR'];
sqlset['sqlall'] = ['ABORT','ABS','ABSENT','ABSOLUTE','ACCESS','ACCORDING','ACTION','ADA','ADD','ADMIN','AFTER','AGGREGATE','ALL','ALLOCATE','ALSO','ALTER','ALWAYS','ANALYSE','ANALYZE','AND','ANY','ARE','ARRAY','ARRAY_AGG','ARRAY_MAX_CARDINALITY','AS','ASC','ASENSITIVE','ASSERTION','ASSIGNMENT','ASYMMETRIC','AT','ATOMIC','ATTRIBUTE','ATTRIBUTES','AUTHORIZATION','AVG','BACKWARD','BASE64','BEFORE','BEGIN','BEGIN_FRAME','BEGIN_PARTITION','BERNOULLI','BETWEEN','BIGINT','BINARY','BIT','BIT_LENGTH','BLOB','BLOCKED','BOM','BOOLEAN','BOTH','BREADTH','BY','CACHE','CALL','CALLED','CARDINALITY','CASCADE','CASCADED','CASE','CAST','CATALOG','CATALOG_NAME','CEIL','CEILING','CHAIN','CHAR','CHARACTER','CHARACTERISTICS','CHARACTERS','CHARACTER_LENGTH','CHARACTER_SET_CATALOG','CHARACTER_SET_NAME','CHARACTER_SET_SCHEMA','CHAR_LENGTH','CHECK','CHECKPOINT','CLASS','CLASS_ORIGIN','CLOB','CLOSE','CLUSTER','COALESCE','COBOL','COLLATE','COLLATION','COLLATION_CATALOG','COLLATION_NAME','COLLATION_SCHEMA','COLLECT','COLUMN','COLUMNS','COLUMN_NAME','COMMAND_FUNCTION','COMMAND_FUNCTION_CODE','COMMENT','COMMENTS','COMMIT','COMMITTED','CONCURRENTLY','CONDITION','CONDITION_NUMBER','CONFIGURATION','CONFLICT','CONNECT','CONNECTION','CONNECTION_NAME','CONSTRAINT','CONSTRAINTS','CONSTRAINT_CATALOG','CONSTRAINT_NAME','CONSTRAINT_SCHEMA','CONSTRUCTOR','CONTAINS','CONTENT','CONTINUE','CONTROL','CONVERSION','CONVERT','COPY','CORR','CORRESPONDING','COST','COUNT','COVAR_POP','COVAR_SAMP','CREATE','CROSS','CSV','CUBE','CUME_DIST','CURRENT','CURRENT_CATALOG','CURRENT_DATE','CURRENT_DEFAULT_TRANSFORM_GROUP','CURRENT_PATH','CURRENT_ROLE','CURRENT_ROW','CURRENT_SCHEMA','CURRENT_TIME','CURRENT_TIMESTAMP','CURRENT_TRANSFORM_GROUP_FOR_TYPE','CURRENT_USER','CURSOR','CURSOR_NAME','CYCLE','DATA','DATABASE','DATALINK','DATE','DATETIME_INTERVAL_CODE','DATETIME_INTERVAL_PRECISION','DAY','DB','DEALLOCATE','DEC','DECIMAL','DECLARE','DEFAULT','DEFAULTS','DEFERRABLE','DEFERRED','DEFINED','DEFINER','DEGREE','DELETE','DELIMITER','DELIMITERS','DENSE_RANK','DEPENDS','DEPTH','DEREF','DERIVED','DESC','DESCRIBE','DESCRIPTOR','DETERMINISTIC','DIAGNOSTICS','DICTIONARY','DISABLE','DISCARD','DISCONNECT','DISPATCH','DISTINCT','DLNEWCOPY','DLPREVIOUSCOPY','DLURLCOMPLETE','DLURLCOMPLETEONLY','DLURLCOMPLETEWRITE','DLURLPATH','DLURLPATHONLY','DLURLPATHWRITE','DLURLSCHEME','DLURLSERVER','DLVALUE','DO','DOCUMENT','DOMAIN','DOUBLE','DROP','DYNAMIC','DYNAMIC_FUNCTION','DYNAMIC_FUNCTION_CODE','EACH','ELEMENT','ELSE','EMPTY','ENABLE','ENCODING','ENCRYPTED','END','END-EXEC','END_FRAME','END_PARTITION','ENFORCED','ENUM','EQUALS','ESCAPE','EVENT','EVERY','EXCEPT','EXCEPTION','EXCLUDE','EXCLUDING','EXCLUSIVE','EXEC','EXECUTE','EXISTS','EXP','EXPLAIN','EXPRESSION','EXTENSION','EXTERNAL','EXTRACT','FALSE','FAMILY','FETCH','FILE','FILTER','FINAL','FIRST','FIRST_VALUE','FLAG','FLOAT','FLOOR','FOLLOWING','FOR','FORCE','FOREIGN','FORTRAN','FORWARD','FOUND','FRAME_ROW','FREE','FREEZE','FROM','FS','FULL','FUNCTION','FUNCTIONS','FUSION','GENERAL','GENERATED','GET','GLOBAL','GO','GOTO','GRANT','GRANTED','GREATEST','GROUP','GROUPING','GROUPS','HANDLER','HAVING','HEADER','HEX','HIERARCHY','HOLD','HOUR','ID','IDENTITY','IF','IGNORE','ILIKE','IMMEDIATE','IMMEDIATELY','IMMUTABLE','IMPLEMENTATION','IMPLICIT','IMPORT','IN','INCLUDING','INCREMENT','INDENT','INDEX','INDEXES','INDICATOR','INHERIT','INHERITS','INITIALLY','INLINE','INNER','INOUT','INPUT','INSENSITIVE','INSERT','INSTANCE','INSTANTIABLE','INSTEAD','INT','INTEGER','INTEGRITY','INTERSECT','INTERSECTION','INTERVAL','INTO','INVOKER','IS','ISNULL','ISOLATION','JOIN','KEY','KEY_MEMBER','KEY_TYPE','LABEL','LAG','LANGUAGE','LARGE','LAST','LAST_VALUE','LATERAL','LEAD','LEADING','LEAKPROOF','LEAST','LEFT','LENGTH','LEVEL','LIBRARY','LIKE','LIKE_REGEX','LIMIT','LINK','LISTEN','LN','LOAD','LOCAL','LOCALTIME','LOCALTIMESTAMP','LOCATION','LOCATOR','LOCK','LOCKED','LOGGED','LOWER','MAP','MAPPING','MATCH','MATCHED','MATERIALIZED','MAX','MAXVALUE','MAX_CARDINALITY','MEMBER','MERGE','MESSAGE_LENGTH','MESSAGE_OCTET_LENGTH','MESSAGE_TEXT','METHOD','MIN','MINUTE','MINVALUE','MOD','MODE','MODIFIES','MODULE','MONTH','MORE','MOVE','MULTISET','MUMPS','NAME','NAMES','NAMESPACE','NATIONAL','NATURAL','NCHAR','NCLOB','NESTING','NEW','NEXT','NFC','NFD','NFKC','NFKD','NIL','NO','NONE','NORMALIZE','NORMALIZED','NOT','NOTHING','NOTIFY','NOTNULL','NOWAIT','NTH_VALUE','NTILE','NULL','NULLABLE','NULLIF','NULLS','NUMBER','NUMERIC','OBJECT','OCCURRENCES_REGEX','OCTETS','OCTET_LENGTH','OF','OFF','OFFSET','OIDS','OLD','ON','ONLY','OPEN','OPERATOR','OPTION','OPTIONS','OR','ORDER','ORDERING','ORDINALITY','OTHERS','OUT','OUTER','OUTPUT','OVER','OVERLAPS','OVERLAY','OVERRIDING','OWNED','OWNER','PAD','PARALLEL','PARAMETER','PARAMETER_MODE','PARAMETER_NAME','PARAMETER_ORDINAL_POSITION','PARAMETER_SPECIFIC_CATALOG','PARAMETER_SPECIFIC_NAME','PARAMETER_SPECIFIC_SCHEMA','PARSER','PARTIAL','PARTITION','PASCAL','PASSING','PASSTHROUGH','PASSWORD','PATH','PERCENT','PERCENTILE_CONT','PERCENTILE_DISC','PERCENT_RANK','PERIOD','PERMISSION','PLACING','PLANS','PLI','POLICY','PORTION','POSITION','POSITION_REGEX','POWER','PRECEDES','PRECEDING','PRECISION','PREPARE','PREPARED','PRESERVE','PRIMARY','PRIOR','PRIVILEGES','PROCEDURAL','PROCEDURE','PROGRAM','PUBLIC','QUOTE','RANGE','RANK','READ','READS','REAL','REASSIGN','RECHECK','RECOVERY','RECURSIVE','REF','REFERENCES','REFERENCING','REFRESH','REGR_AVGX','REGR_AVGY','REGR_COUNT','REGR_INTERCEPT','REGR_R2','REGR_SLOPE','REGR_SXX','REGR_SXY','REGR_SYY','REINDEX','RELATIVE','RELEASE','RENAME','REPEATABLE','REPLACE','REPLICA','REQUIRING','RESET','RESPECT','RESTART','RESTORE','RESTRICT','RESULT','RETURN','RETURNED_CARDINALITY','RETURNED_LENGTH','RETURNED_OCTET_LENGTH','RETURNED_SQLSTATE','RETURNING','RETURNS','REVOKE','RIGHT','ROLE','ROLLBACK','ROLLUP','ROUTINE','ROUTINE_CATALOG','ROUTINE_NAME','ROUTINE_SCHEMA','ROW','ROWS','ROW_COUNT','ROW_NUMBER','RULE','SAVEPOINT','SCALE','SCHEMA','SCHEMA_NAME','SCOPE','SCOPE_CATALOG','SCOPE_NAME','SCOPE_SCHEMA','SCROLL','SEARCH','SECOND','SECTION','SECURITY','SELECT','SELECTIVE','SELF','SENSITIVE','SEQUENCE','SEQUENCES','SERIALIZABLE','SERVER','SERVER_NAME','SESSION','SESSION_USER','SET','SETOF','SETS','SHARE','SHOW','SIMILAR','SIMPLE','SIZE','SKIP','SMALLINT','SNAPSHOT','SOME','SOURCE','SPACE','SPECIFIC','SPECIFICTYPE','SPECIFIC_NAME','SQL','SQLCODE','SQLERROR','SQLEXCEPTION','SQLSTATE','SQLWARNING','SQRT','STABLE','STANDALONE','START','STATE','STATEMENT','STATIC','STATISTICS','STDDEV_POP','STDDEV_SAMP','STDIN','STDOUT','STORAGE','STRICT','STRIP','STRUCTURE','STYLE','SUBCLASS_ORIGIN','SUBMULTISET','SUBSTRING','SUBSTRING_REGEX','SUCCEEDS','SUM','SYMMETRIC','SYSID','SYSTEM','SYSTEM_TIME','SYSTEM_USER','TABLE','TABLES','TABLESAMPLE','TABLESPACE','TABLE_NAME','TEMP','TEMPLATE','TEMPORARY','TEXT','THEN','TIES','TIME','TIMESTAMP','TIMEZONE_HOUR','TIMEZONE_MINUTE','TO','TOKEN','TOP_LEVEL_COUNT','TRAILING','TRANSACTION','TRANSACTIONS_COMMITTED','TRANSACTIONS_ROLLED_BACK','TRANSACTION_ACTIVE','TRANSFORM','TRANSFORMS','TRANSLATE','TRANSLATE_REGEX','TRANSLATION','TREAT','TRIGGER','TRIGGER_CATALOG','TRIGGER_NAME','TRIGGER_SCHEMA','TRIM','TRIM_ARRAY','TRUE','TRUNCATE','TRUSTED','TYPE','TYPES','UESCAPE','UNBOUNDED','UNCOMMITTED','UNDER','UNENCRYPTED','UNION','UNIQUE','UNKNOWN','UNLINK','UNLISTEN','UNLOGGED','UNNAMED','UNNEST','UNTIL','UNTYPED','UPDATE','UPPER','URI','USAGE','USER','USER_DEFINED_TYPE_CATALOG','USER_DEFINED_TYPE_CODE','USER_DEFINED_TYPE_NAME','USER_DEFINED_TYPE_SCHEMA','USING','VACUUM','VALID','VALIDATE','VALIDATOR','VALUE','VALUES','VALUE_OF','VARBINARY','VARCHAR','VARIADIC','VARYING','VAR_POP','VAR_SAMP','VERBOSE','VERSION','VERSIONING','VIEW','VIEWS','VOLATILE','WHEN','WHENEVER','WHERE','WHITESPACE','WIDTH_BUCKET','WINDOW','WITH','WITHIN','WITHOUT','WORK','WRAPPER','WRITE','XML','XMLAGG','XMLATTRIBUTES','XMLBINARY','XMLCAST','XMLCOMMENT','XMLCONCAT','XMLDECLARATION','XMLDOCUMENT','XMLELEMENT','XMLEXISTS','XMLFOREST','XMLITERATE','XMLNAMESPACES','XMLPARSE','XMLPI','XMLQUERY','XMLROOT','XMLSCHEMA','XMLSERIALIZE','XMLTABLE','XMLTEXT','XMLVALIDATE','YEAR','YES','ZONE'];

var numset = [];
numset['complex'] = ['零', '壹', '贰', '叁', '肆', '伍', '陆', '柒', '捌', '玖', '拾'];
numset['simple'] = ['〇', '一', '二', '三', '四', '五', '六', '七', '八', '九', '十'];

function num2money(n) {
    n = n.trim();
    if (!/^(0|[1-9]\d*)(\.\d+)?$/.test(n)) return '无效数值';
    var unit = '仟佰拾兆仟佰拾亿仟佰拾万仟佰拾元角分厘豪丝', str = '';
    n += '00000';
    var p = n.indexOf('.');
    if (p >= 0) n = n.substring(0, p) + n.substr(p + 1, 5);
    unit = unit.substr(unit.length - n.length);
    for (var i = 0; i < n.length; i++) str += '零壹贰叁肆伍陆柒捌玖'.charAt(n.charAt(i)) + unit.charAt(i);
    str = str.replace(/零(仟|佰|拾)/g, '零').replace(/(零)+/g, '零').replace(/零(万|亿|元)/g, '$1').replace(/(亿)万|壹(拾)/g, '$1$2').replace(/^元零?|零角|零分|零厘|零豪|零丝/g, '').replace(/元$/g, '元整');
    return str;
}

function money2num(n) {
    n = n.trim();
    //if (!/^[零壹贰叁肆伍陆柒捌玖][仟佰拾兆仟佰拾亿仟佰拾万仟佰拾元角分厘豪丝]?$/.test(n)) return '无效金额';
    n = n.replace(/(^拾)/g, '壹$1');
    n = n.replace(/(.角)/g, '.$1');
    n = n.replace(/[兆亿万仟佰拾元角分厘豪丝整]/g, '');
    var str = n.replace(/零/g, '0').replace(/壹/g, '1').replace(/贰/g, '2').replace(/叁/g, '3').replace(/肆/g, '4').replace(/伍/g, '5').replace(/陆/g, '6').replace(/柒/g, '7').replace(/捌/g, '8').replace(/玖/g, '9');
    str = (/^(0|[1-9]\d*)(\.\d+)?$/.test(str)) ? str : '无效金额';
    return str;
}